init commit
RomanGiulambarian/more-energy pull request #1
Opened 2024-02-19 12:11 UTC by RomanGiulambarian

2024-02-21 13:51 UTC, UndefinedOleg requested changes
Оставил пару комментов

2024-02-21 13:51 UTC, UndefinedOleg commented on .dockerignore
> +/pgdata
Add empty line

2024-02-21 13:51 UTC, UndefinedOleg commented on .gitignore
> +pgdata
Empty line

2024-02-21 13:51 UTC, UndefinedOleg commented on .prettierrc
> +}
Empty line

2024-02-21 13:51 UTC, UndefinedOleg commented on Dockerfile
> +CMD [ "npm", "run", "start:dev" ]
Empty line

2024-02-21 13:51 UTC, UndefinedOleg commented on src/app.module.ts
> +import { User } from './users/entities/user.entity';
Давай внешние зависимости ставить сверху, потом пустая строка и ниже наши зависимости

2024-02-21 13:51 UTC, UndefinedOleg commented on src/app.module.ts
> +      envFilePath: '.env',
Можно удалить значение по умолчанию

2024-02-21 13:51 UTC, UndefinedOleg commented on src/app.module.ts
> +        synchronize: false,
строку synchronize давай тоже удалим, она по умолчанию false

2024-02-21 13:51 UTC, UndefinedOleg commented on src/db/entities/common.entity.ts
> +}
Мы ещё хотели updatedAt и deletedAt

2024-02-21 13:51 UTC, UndefinedOleg commented on src/main.ts
> +import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
Отсортируй импорты (сначала внешние, потом пустая строка, потом наши)

2024-02-21 13:51 UTC, UndefinedOleg commented on src/db/entities/health-vision.entyty.ts
> +}
Возможно какие то из полей можно сделать в enum, пройди по всем сущностям посмотри подобные моменты

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/dto/create-user.dto.ts
> +  photoPath?: string;
Опциональные поля в ДТО помечаем декоратором IsOptional(), иначе они в сваггер не попадут

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.controller.ts
> +  }
else блок можно убрать, т.к. код ниже пойдёт только если user будет

if (!user) {
      throw new NotFoundException('User does not exist');
    } 
    return user;

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.controller.ts
> +    await this.userService.remove(id);
давай использовать softRemove - он будет проставлять дату удаления в поле deletedAt. Также везде при поиске добавь условия чтоб искал только такие записи, в которых deletedAt = Null

Вот пример:
const docInstance = await this.docsRepository.findOne({
      where: {
        id,
        deleted_at: IsNull(),
      }
    })

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.controller.ts
> +    res.status(204).send().end();
а здесь не получится сделать просто return и навесить на контроллере декоратор со статусом 204?

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.controller.ts
> +    res.status(204).send().end();
И давай возвращать айди удалённой сущности

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.service.ts
> +import * as bcrypt from 'bcryptjs';
Давай отсортируем)

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.service.ts
> +  async create(createUserDto: CreateUserDto): Promise<User> {
можно убрать async

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.service.ts
> +    return this.userRepository.create(createUserDto).save();
можно делать сразу .save(createUserDto) без .create

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.service.ts
> +  async findAll(): Promise<User[]> {
можно убрать асинк

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.service.ts
> +    return await this.userRepository.findOne({
async и await можно убрать - нест под капотом результаты сервисов эвэйтит

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.service.ts
> +    return updateUser;
давай сразу return this.userRepository...

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.service.ts
> +  // }
Комментарии лучше не пушить, кроме тех, которые явно нужны (в том числе и участки кода)

2024-02-21 13:51 UTC, UndefinedOleg commented on src/users/users.service.ts
> +    return await this.userRepository
Можно убрать async/await

2024-02-21 14:37 UTC, RomanGiulambarian commented on src/users/users.controller.ts
> +    await this.userService.remove(id);
Там по идее не попадает в выборку удаленные посты без флага withDeleted: true

2024-02-23 10:02 UTC, UndefinedOleg approved these changes

2024-02-26 06:43 UTC, merged