add crud for exercisesteps
RomanGiulambarian/more-energy pull request #3
Opened 2024-02-22 14:19 UTC by RomanGiulambarian

2024-02-23 09:58 UTC, UndefinedOleg requested changes

2024-02-23 09:58 UTC, UndefinedOleg commented on src/db/migrations/1708600511281-update-exercise-exercisesteps.ts
> +export class UpdateExerciseExercisesteps1708600511281 implements MigrationInterface {
Перепроверь миграции, возможно у тебя тут логика от другой фичи (userCoach). Когда генерируешь миграцию убедись, что все уже имеющиеся "накатаны"

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise-steps/dto/create-exercise-step.dto.ts
> +  position: number;
Давай валидировать IsString() IsNumber()

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise-steps/exercise-steps.service.ts
>      private readonly exerciseStepsRepository: Repository<ExerciseSteps>,
Разве не надо это делать в конструкторе и с использованием @InjectRepository()

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise-steps/exercise-steps.service.ts
> +    return this.exerciseStepsRepository.findOne({ where: { id } });
Давай использовать .findOneBy({id})

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise-steps/exercise-steps.service.ts
> +    await this.exerciseStepsRepository.softRemove(exercise);
Давай что нибудь возвращать после удаления и восстановления, хотя бы  true для начала

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise/exercise.controller.ts
> +import { CreateExerciseStepDto } from 'src/exercise-steps/dto/create-exercise-step.dto';
Давай отсортируем

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise/exercise.controller.ts
> +  ) {}
Давай в таких местах явно писать @Inject(ExerciseService) private...

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise/exercise.controller.ts
>    async findAll() {
Можно опустить async/await

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise/exercise.controller.ts
>    async softRemove(@Param('id') id: string) {
везде где в @Param передается id сделай валидацию на UUID

@Param('id', new ParseUUIDPipe) id: string)

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise/exercise.controller.ts
> +  }
Давай возвращать true

2024-02-23 09:58 UTC, UndefinedOleg commented on src/exercise/exercise.service.ts
>    }
Давай что нибудь возвращать

2024-02-26 17:07 UTC, UndefinedOleg requested changes

2024-02-26 17:07 UTC, UndefinedOleg commented on src/exercise-steps/entities/exercise-steps.entity.ts
> +  @IsString()
А зачем здесь IsString итд? Так можно делать если ентити и как дто используем, но вроде тут такого нет

2024-02-26 17:07 UTC, UndefinedOleg commented on src/exercise-steps/exercise-steps.service.ts
> +    return { id, deleted: true };
Давай сделаем ResponseDto с конструктором и будем возвращать его новый инстанс

export class DeletedResponseDto {
constructor(
id: string
) {
this.id = id;
}
id: string;
deleted: boolean;
}

return new DeletedResponseDto(id)l

2024-02-26 17:07 UTC, UndefinedOleg commented on src/exercise-steps/exercise-steps.service.ts
> +  async softRemove(id: string): Promise<object> {
Здесь добавим наш респонсДто (ниже коммент)

2024-02-26 17:07 UTC, UndefinedOleg commented on src/exercise/exercise.service.ts
> +    return { id, deleted: true };
Тоже респонсДто

2024-02-27 07:12 UTC, RomanGiulambarian commented on src/exercise-steps/entities/exercise-steps.entity.ts
> +  @IsString()
тупанул

2024-02-28 17:12 UTC, UndefinedOleg approved these changes

2024-02-29 10:54 UTC, merged